### PR TITLE
[DO NOT MERGE] Error when loading wasm

### PR DESCRIPTION
**Pull request by mhchia**
## Issue Encountered
When incorporating bind_prover from the tlsn-prover dev branch in this PR, I encountered an error in the final execution stage.

Although both `wasm-pack build --target web` and `webpack-dev-server` compile without issues, the page crashes upon loading, failing to execute the wasm code. The detailed error message is shown in the screenshot.

https://github.com/tlsnotary/tlsn-extension/blob/1da8d5d2a4f13b9cbb9202f78aeec0d7cf3e5f96/src/lib.rs#L43-L45

Both `wasm-pack build --target web` and `webpack-dev-server` work. However, when opening the page, I got the following error, which failed to run the wasm code.

image

The issue appears to involve the `GFp_x25519_sc_reduce` function from the `ring` crate, which currently does not compile to wasm ([known issue](https://github.com/briansmith/ring/issues/918)). As `tlsn-prover` currently relies on the ring crate indirectly, this prevents proper execution of the wasm code. The `ring` dependency chain is demonstrated by the following dependency tree:

```bash
# Ran under the project root of `tlsn`. This lists dependencies other than dev-dependencies which depend on `ring` crate.
% cargo tree -i ring -e normal,build
ring v0.16.20
├── rustls-webpki v0.100.1
│   └── webpki-roots v0.23.1
│       ├── tlsn-core v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/tlsn/tlsn-core)
│       │   ├── tlsn-notary v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/tlsn/tlsn-notary)
│       │   └── tlsn-prover v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/tlsn/tlsn-prover)
│       └── tlsn-prover v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/tlsn/tlsn-prover)
├── sct v0.7.0
│   ├── tlsn-tls-client v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-client)
│   │   ├── tlsn-prover v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/tlsn/tlsn-prover)
│   │   └── tlsn-tls-client-async v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-client-async)
│   │       └── tlsn-prover v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/tlsn/tlsn-prover)
│   └── tlsn-tls-core v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-core)
│       ├── tlsn-core v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/tlsn/tlsn-core) (*)
│       ├── tlsn-prover v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/tlsn/tlsn-prover)
│       ├── tlsn-tls-backend v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-backend)
│       │   ├── tlsn-tls-client v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-client) (*)
│       │   └── tlsn-tls-mpc v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-mpc)
│       │       ├── tlsn-notary v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/tlsn/tlsn-notary)
│       │       └── tlsn-prover v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/tlsn/tlsn-prover)
│       ├── tlsn-tls-client v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-client) (*)
│       └── tlsn-tls-mpc v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-mpc) (*)
├── tlsn-tls-client v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-client) (*)
├── tlsn-tls-core v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-core) (*)
└── webpki v0.22.0
    ├── tlsn-tls-client v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-client) (*)
    └── tlsn-tls-core v0.1.0 (/Users/mhchia/projects/work/pse/tlsn/components/tls/tls-core) (*)
```

## Reproduction Steps

To reproduce the issue, follow these steps:
1. Clone the repo and checkout to this branch
```bash
git clone git@github.com:tlsnotary/tlsn-extension.git
git checkout mhchia/exploring-wasm-bindgen
```

2. Install wasm-pack if it is not already installed.

```bash
yarn global add wasm-pack
```

3. Run `yarn build-and-start` to build the project, generate bindings with wasm-bindgen, and start a webserver on port `8080`.

```bash
yarn build-and-start
```

4. Open the page at `http://localhost:8080` in the browser.

```bash
open http://localhost:8080
```

4. The error message should now be visible on the page.

## Potential Solution
Based on offline discussions, one potential solution would be to replace `ring` with an alternative that supports wasm compilation.

### CODE REVIEW

**Comment by mhchia** [comment]
## Current Status
Both notary and tlsn-extension (tlsn-prover) are stuck 

## Steps to Reproduce
### 1. Run websocket proxy
```bash
docker run -it --rm -p 55688:80 novnc/websockify 80 twitter.com:443
```

### 2. Run notary server in twitter example
```bash
git clone git@github.com:mhchia/tlsn.git && git checkout tlsn-examples-ws
cd tlsn/examples
RUST_LOG=trace,yamux=info cargo run --release --example notary
```

### 3. Setup tlsn extension
Install wasm-pack
```bash
yarn global add wasm-pack
```
Build wasm and start webserver
```bash
git clone git@github.com:tlsnotary/tlsn-extension.git && git checkout mhchia/exploring-wasm-bindgen
yarn build-and-start
```

### 4. Open the page (Prover)
```bash
open http://localhost:8080
```

## Logs
### Prover
You should be able to see the following in the console (F12)
```console
!@# 0
!@# 1
2023-08-09T13:13:10.408Z DEBUG yamux::connection: new connection: a2f9bb69 (Client)    
2023-08-09T13:13:10.414000128Z DEBUG yamux::connection: a2f9bb69: new outbound (Stream a2f9bb69/1) of (Connection a2f9bb69 Client (streams 0))    
2023-08-09T13:13:10.415000064Z DEBUG yamux::connection: a2f9bb69: new outbound (Stream a2f9bb69/3) of (Connection a2f9bb69 Client (streams 1))    
2023-08-09T13:13:10.419000064Z DEBUG yamux::connection: a2f9bb69: new outbound (Stream a2f9bb69/5) of (Connection a2f9bb69 Client (streams 2))    
2023-08-09T13:13:10.419000064Z DEBUG yamux::connection: a2f9bb69: new outbound (Stream a2f9bb69/7) of (Connection a2f9bb69 Client (streams 3))   
```

### Notary
You should see the something like the below (details can be seen [here](https://gist.github.com/mhchia/6923ed5422a9e16fc608381e81a11a5f#file-logs-notary-txt))
```
% RUST_LOG=trace,yamux=info cargo run --release --example notary
...
Listening on: 127.0.0.1:7788
Accepted connection from: 127.0.0.1:65478
2023-08-09T12:55:19.932099Z TRACE tungstenite::handshake::server: Server handshake initiated.    
2023-08-09T12:55:19.932167Z TRACE tungstenite::handshake::machine: Doing handshake round.    
2023-08-09T12:55:19.932389Z TRACE tungstenite::handshake::machine: Doing handshake round.    
2023-08-09T12:55:19.932458Z DEBUG tungstenite::handshake::server: Server handshake done.    
2023-08-09T12:55:19.932777Z TRACE tungstenite::protocol: Frames still in queue: 0    
2023-08-09T12:55:19.932805Z TRACE tungstenite::protocol: Frames still in queue: 0    
!@# notarize: 0
!@# notarize: 1
!@# notarize: 2

...

2023-08-09T12:55:19.943526Z TRACE tungstenite::protocol: Received message ot/1/parent    
2023-08-09T12:55:19.943534Z TRACE tungstenite::protocol: Frames still in queue: 0    
2023-08-09T12:55:19.943538Z TRACE tungstenite::protocol: Frames still in queue: 0    
2023-08-09T12:55:19.943572Z TRACE tungstenite::protocol: Frames still in queue: 0    
2023-08-09T12:55:19.943576Z TRACE tungstenite::protocol: Frames still in queue: 0    
2023-08-09T12:55:19.943585Z TRACE tungstenite::protocol: Frames still in queue: 0    
2023-08-09T12:55:19.943588Z TRACE tungstenite::protocol: Frames still in queue: 0    
2023-08-09T12:55:19.943755Z TRACE tungstenite::protocol: Frames still in queue: 0    
2023-08-09T12:55:19.943770Z TRACE tungstenite::protocol: Frames still in queue: 0    
!@# notarize: 3
2023-08-09T12:55:19.943834Z  INFO tlsn_notary: Created OT senders and receivers
!@# notarize: 27
!@# notarize: 28
!@# notarize: 29
!@# notarize: loop start
!@# notarize: 4
!@# notarize: 5: encoder_seed: [96, 215, 192, 173, 80, 65, 210, 138, 97, 163, 217, 79, 2, 30, 207, 132, 13, 66, 82, 126, 182, 96, 143, 97, 33, 96, 119, 37, 210, 252, 185, 51]
2023-08-09T12:55:19.944003Z TRACE tokio_util::codec::framed_impl: flushing framed transport
2023-08-09T12:55:19.944009Z TRACE tokio_util::codec::framed_impl: writing; remaining=37
2023-08-09T12:55:19.944016Z TRACE tokio_util::codec::framed_impl: framed transport flushed
2023-08-09T12:55:19.944459Z TRACE tungstenite::protocol: Frames still in queue: 0    
2023-08-09T12:55:19.944481Z TRACE tungstenite::protocol: Frames still in queue: 0    
2023-08-09T12:55:19.944489Z TRACE tungstenite::protocol: Frames still in queue: 1    
2023-08-09T12:55:19.944494Z TRACE tungstenite::protocol: Sending frame: Frame { header: FrameHeader { is_final: true, rsv1: false, rsv2: false, rsv3: false, opcode: Data(Binary), mask: None }, payload: [0, 0, 0, 2, 0, 0, 0, 7, 0, 0, 0, 37] }    
2023-08-09T12:55:19.944504Z TRACE tungstenite::protocol::frame: writing frame 

```

**Comment by chcharcharlie** [comment]
Not sure how useful it is, but I added a bit more logs and found that both sender setup and receiver setup are getting stuck at the `parent_ot.rand_setup` step: https://github.com/mhchia/tlsn/blob/0213adf7b547ae75977a9f195c862b7a539136d3/components/actors/actor-ot/src/sender.rs#L104.

**Comment by chcharcharlie** [comment]
> Not sure how useful it is, but I added a bit more logs and found that both sender setup and receiver setup are getting stuck at the `parent_ot.rand_setup` step: https://github.com/mhchia/tlsn/blob/0213adf7b547ae75977a9f195c862b7a539136d3/components/actors/actor-ot/src/sender.rs#L104.

Digged a bit further and it seems to be Backend::spawn not really spawning up and running anything here: https://github.com/privacy-scaling-explorations/mpz/blob/dev/ot/mpz-ot/src/kos/sender.rs#L42.

I guess initially if we were able to get wasm-bindgen-rayon to help translate this into webworkers this will be able to work, but that path always fails with the websocket close issue, so I guess we will have to get around it?

**Comment by mhchia** [comment]
Just a note for the recent changes. Now the prover can run without rayon. It takes ~350 seconds.

## Changes
- tlsn-utils: use [single cpu backend](https://github.com/mhchia/tlsn-utils/commit/46327f0e7648dfd6ccd18c49e6699d4535622f28) over rayon
- tlsn (branch [tlsn-examples-ws-single-cpu-backend](https://github.com/mhchia/tlsn/tree/tlsn-examples-ws-single-cpu-backend), [diff](https://github.com/tlsnotary/tlsn/compare/4a340a04a6fcf4c283406daaea3be8b368ddb82c...mhchia:tlsn:tlsn-examples-ws-single-cpu-backend))
    - Use the modified tlsn-utils
    - Use [web-time](https://crates.io/crates/web-time) over `std::time`
        - `web-time` is used here since it provides the same API as `std::time` and it's easier to port existing code
        - We can probably use [time](https://crates.io/crates/time) or [instant](https://crates.io/crates/instant) since they seem to support wasm and they are a lot more popular 
- tlsn-extension (branch mhchia/exploring-wasm-bindgen)
    - Use `wasm-bingen-futures::spawn_local` over `tokio::spawn`
    - Run tln-prover operations from twitter example

image

## Reproduce
Follow the steps in https://github.com/tlsnotary/tlsn-extension/pull/1#issuecomment-1671311923, but `tlsn` must checkout to the branch [tlsn-examples-ws-single-cpu-backend](https://github.com/mhchia/tlsn/tree/tlsn-examples-ws-single-cpu-backend).

**Comment by 0xtsukino** [comment]
merged with #4

**Pull request closed without merging**
